[build]
  # Build command to run
  command = "npm run build"
  
  # Directory to publish (relative to the repository root)
  publish = "dist"
  
  # Functions directory
  functions = "netlify/functions"
  
  # Node.js version to use for build
  [build.environment]
    NODE_VERSION = "18"

# API redirects for Netlify Functions (MUST come before SPA redirect)
[[redirects]]
  from = "/api/cards"
  to = "/.netlify/functions/cards"
  status = 200
  force = true

[[redirects]]
  from = "/api/cards/:id"
  to = "/.netlify/functions/card"
  status = 200
  force = true

# Redirects for SPA (Single Page Application) - MUST come after API redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for better performance and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache HTML files
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate" 